repos:
- repo: local
  hooks:
    - id: cargo-fmt
      name: Format Rust
      entry: bash -c 'cargo fmt'
      language: system
      types: [rust]
      pass_filenames: false

    - id: cargo-check
      name: Type check Rust
      entry: bash -c 'cargo check'
      language: system
      types: [rust]
      pass_filenames: false
